"""Aggregate final results into docs/results.md."""
from __future__ import annotations

import argparse
import itertools
import json
import subprocess
import sys
from pathlib import Path


def load(p):
    return json.loads(Path(p).read_text()) if Path(p).exists() else None


def fmt(x):
    return f"{x:.2f}" if isinstance(x, float) else str(x)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--prefix", default="final")
    ap.add_argument("--out", default="docs/results.md")
    a = ap.parse_args()
    rows = load(f"runs/{a.prefix}_results.json") or []
    base = load("runs/baselines.json") or []
    cross = load("runs/crossui.json") or []
    out = ["# Results", "", "Generated by `python -m semabi.report`. All runs: 3 random episodes x 30 steps, then 3 active rounds x 100 primitives, "
           "then 6 held-out goals. Operator recovery uses the paired-state evaluator (effect agreement >= 0.9); "
           "precision = recovered / learned operators.", ""]
    out += ["## SemABI across UIs, label modes and rule variants", "",
            "| run | types | predicates | operators | precision | pre-agree | eff-agree | goals | primitives |", "|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        out.append(f"| {r['run']} | {r['types']} | {fmt(r['preds'])} | {r['ops']} | {fmt(r['op_precision'])} | {fmt(r['pre_agree'])} | {fmt(r['eff_agree'])} | {r['goals']} | {r['primitives']} |")
    if base:
        out += ["", "## Baselines (direct structural scorer: operator counted only if pre-agree >= 0.9 and eff-agree >= 0.9)", "",
                "| run | SemABI ops (prec/pre/eff) | LLM passive ops (prec/pre/eff) | known-vocab ops (pre/eff) | screen graph: held-out next-screen predicted |", "|---|---|---|---|---|"]
        for b in base:
            s, l, k, g = b["semabi"], b.get("llm", {}), b["known_vocab"], b["graph"]
            ls = f"{l.get('ops','-')} ({fmt(l.get('precision','-'))}/{fmt(l.get('pre','-'))}/{fmt(l.get('eff','-'))})" if "ops" in l else "failed"
            out.append(f"| {b['run']} | {s['ops']} ({fmt(s['precision'])}/{fmt(s['pre'])}/{fmt(s['eff'])}) | {ls} | {k['ops']} ({fmt(k['pre'])}/{fmt(k['eff'])}) | {fmt(g.get('next_screen_predicted', '-'))} |")
    if cross:
        out += ["", "## Cross-UI structural equivalence (learned model vs learned model, no hidden information)", "",
                "| A | B | A-operators matched in B | B operators | score |", "|---|---|---|---|---|"]
        for c in cross:
            out.append(f"| {c['a']} | {c['b']} | {c['equivalent']}/{c['ops_a']} | {c['ops_b']} | {fmt(c['score'])} |")
    Path(a.out).write_text("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
